name: models
description: Модели данных
version: 1.0.0

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^5.0.0
  freezed: ^2.4.7
