name: remote_api
description: Реализация репозиториев для работы с АПИ
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  api:
    path: ../api
  models:
    path: ../models
  repository:
    path: ../repository
  dio: ^5.4.0 
dev_dependencies:
  flutter_lints: ^5.0.0
