name: repository_mocks
description: Моки для репозиториев
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  models:
    path: ../models 
  repository:
    path: ../repository 

dev_dependencies:
  flutter_lints: ^5.0.0
